### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by r3na** [wesleytodd/express-openapi#28]

**Comment by wesleytodd** [comment]
Hi, I have been checking in once in a while. I have generally pulled back from my OSS work due to some burnout a few years ago, but AFAIK this library is in decent shape. There are a few edge case bugs I would accept PR's for, and I am going to go through the open PR's now to see if any of them are addressed.

As a note for you in the future: these kinds of issues are generally considered bad form. Not only is the definition of "alive" really ambiguous, it is not a constructive conversation starter. Like did you find a bug? Do you want to contribute? What? In reality what you are doing is forcing maintainers to take on the emotional labor of answering you or just ignore it and actaully abandon the work. I would strongly encourage you to refrain from opening issues like this in the future.

**Comment by wesleytodd** [comment]
Hey, I will add, I am happy to look at bringing on more contributors to pick up the slack of my lack of attention. If that is something you are interested in, feel free to open an issue about it, and likely I would hope to see some contribution ideas you have. I can also setup a "triage" role if that is more up your alley to help answer issues and plan for changes.
