### ISSUE TITLE
Use With Express Router

### ISSUE THREAD

**Issue by hrtejada** [wesleytodd/express-openapi#7]
Can this be used with an Express Router? If so, can you share an example and/or update the documentation?

**Comment by wesleytodd** [comment]
Hi @hrtejada, yes it can be used with the Express Router.  I am guessing since you are asking for an example you mean specifically with `express.Router` or `require('router')`.  So for that all you need to do is swap out `app` with `router` in the examples in the readme.  If there is something to help make it more clear you think we should add to the readme I would happily accept a PR!

**Comment by bjyurkovich** [comment]
@hrtejada @wesleytodd 

See https://github.com/wesleytodd/express-openapi/pull/8

Hopefully that helps (we are using in one of our apps currently).

**Comment by wesleytodd** [comment]
Feature added in `0.1.0`
